---
title: "Brain Stimulated MOO"
author: "Bastien Boutonnet"
date: "17 December 2014"
output: html_document
---

**TODO:**
- find a better visualisation group by mooney difficulty?

```{r echo=FALSE}
library(ggplot2)
library(lme4)
library(plyr)
library(dplyr)
library(car)
library(lmSupport)

dat <- read.csv("brainStimMOOAllVars.csv",header=T)
dat$electrode <- as.factor(dat$electrode)
dat$elec <- varRecode(dat$electrode, c(1,2,3),c("Anodal","Cathodal","No Stimulation"))
elimPpts <- c("WFM102","WFM104",'WFM106','WFM107','WFM127','wfm127','WFM131','WFM133','WFM132','WFM138')
dat <- dat[!(dat$subjcode %in% elimPpts),]

#CIs Function
getCIs<- function (x,n) {
  binom.test(round(x*n,0),n)$conf.int[1:2]
}

byParticipant <- ddply(dat, c("subjcode"), summarise, 
                       acc=mean(isCorrect,na.rm=T))

#Summarise by Mooney for plot essentially.
byMooney <- ddply(dat, c('Name','elec'), summarise,
                  acc=mean(isCorrect, na.rm=T),
                  rt=mean(Timing_1, na.rm=T),
                  conf=mean(Confidence, na.rm=T))
```

#Naming Accuracy by Mooney
```{r echo=FALSE}
#Compute CIs
CIs = sapply(byMooney$acc,getCIs,n=9)
limits <- aes(ymin = CIs[1,], ymax=CIs[2,])
```

```{r echo=FALSE}
#Plot Data
##Style options for the graph
PimpMyPlot <- theme(text=element_text(size=14,family="Helvetica"))+
  theme(axis.line=element_line(colour='black'))+
  theme(axis.text=element_text(colour="black"))+
  theme(panel.grid.major.y=element_line(linetype='dotted',colour='grey50',size=0.3))+
  theme(panel.grid.major.x=element_line(linetype='dashed',colour='grey50',size=0.3))+
  theme(panel.background=element_blank())

#Reorder for Graph
#ORDER X Axis by Free Naming Accuracy of No Stim group
vals = byMooney[ byMooney$elec == "No Stimulation",]
xvals = vals[with(vals, order(-acc)), ]$Name
byMooney$mooneyReord <- factor(byMooney$Name, levels = xvals)
```

```{r fig.width=9}
ggplot(byMooney, aes(x=mooneyReord,y=acc,colour=elec,group=elec))+
  geom_point(size=3)+
  geom_line()+
  #geom_errorbar(limits,width=.2)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(x ="Picture",y="Accuracy")+
  PimpMyPlot
```

#Median Split
```{r}
byMooneyNoStim <- ddply(subset(dat, electrode==3), c('Name'), summarise,
                  acc=mean(isCorrect, na.rm=T))
byMooneyNoStim$MedSplit <- as.integer(byMooneyNoStim$acc>median(byMooneyNoStim$acc))
byMooneyNoStim$QrtSplit <- with(byMooneyNoStim, cut(acc, 
                                breaks=quantile(acc, probs=seq(0,1, by=0.25)), 
                                include.lowest=TRUE))
byMooneyNoStim=byMooneyNoStim[c("Name","MedSplit","QrtSplit")]
SplitDat <- merge(dat,byMooneyNoStim)
SplitDat$QrtSplit <- as.factor(SplitDat$QrtSplit)

ggplot(SplitDat, aes(x=QrtSplit,y=isCorrect,fill=elec))+
  stat_summary(fun.y=mean, geom="bar",position=position_dodge(0.95))+
  stat_summary(fun.data=mean_se, geom="errorbar",position=position_dodge(0.95),width=.2)
```

#Predicting Accuracy from Stimulation Condition

```{r}
dat$elecCent <- varRecode(dat$elec, c("Anodal","Cathodal","No Stimulation"),c(1,0,-1))
m <- glmer(isCorrect~elecCent+(1|Name),data=dat,family='binomial')
summary(m)
```
